version: '3.1'

services:
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mariadb-root-password
      - MYSQL_PASSWORD_FILE=/run/secrets/mariadb-db-password
      - MYSQL_DATABASE=butler
      - MYSQL_USER=butler
    secrets:
      - mariadb-root-password
      - mariadb-db-password
  influxdb:
    environment:
      - INFLUXDB_ADMIN_PASSWORD_FILE=/run/secrets/influxdb-root-password
      - INFLUXDB_USER_PASSWORD_FILE=/run/secrets/influxdb-db-password
      - INFLUXDB_DB=butler
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_USER=butler
    secrets:
      - influxdb-root-password
      - influxdb-db-password

secrets:
  mariadb-root-password:
    file: $BUTLER_HOME/mariadb/root-password
  influxdb-root-password:
    file: $BUTLER_HOME/influxdb/root-password
