version: '3.1'

services:
  mosquitto:
    image: $BUTLER_IMG_MOSQUITTO
    depends_on:
      - api
    command:
      - sh
      - -c
      - >-
        envsubst '\$$BUTLER_HOST' < /mosquitto/config/conf.d.in/auth.conf.in > /mosquitto/config/conf.d/auth.conf
        &&
        /run.sh mosquitto-app -c /mosquitto/config/mosquitto.conf
    environment:
      - MOSQUITTO_UID=$BUTLER_MOSQUITTO_UID
      - MOSQUITTO_GID=$BUTLER_MOSQUITTO_GID
      - BUTLER_HOST
    volumes:
      - mosquitto-data:/mosquitto/data:rw
      - $BUTLER_HOME/mosquitto/conf.d/log.conf:/mosquitto/config/conf.d/log.conf:ro
      - $BUTLER_HOME/mosquitto/conf.d/ssl.conf:/mosquitto/config/conf.d/ssl.conf:ro
      - $BUTLER_HOME/mosquitto/conf.d/websockets.conf:/mosquitto/config/conf.d/websockets.conf:ro
      - $BUTLER_HOME/mosquitto/conf.d/auth.conf.in:/mosquitto/config/conf.d.in/auth.conf.in:ro
      - $BUTLER_HOME/cert/ca/ca.crt.pem:/mosquitto/config/cert/ca.crt.pem:ro
      - $BUTLER_HOME/cert/srv/$BUTLER_HOST/$BUTLER_HOST.crt.pem:/mosquitto/config/cert/crt.pem:ro
      - $BUTLER_HOME/cert/srv/$BUTLER_HOST/$BUTLER_HOST.key.pem:/mosquitto/config/cert/key.pem:ro
    restart: unless-stopped

  mariadb:
    image: $BUTLER_IMG_MARIADB
    environment:
      - MYSQL_UID=$BUTLER_MYSQL_UID
      - MYSQL_GID=$BUTLER_MYSQL_GID
    secrets:
      - mariadb-root-options
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --defaults-extra-file=/run/secrets/mariadb-root-options -h localhost ping"]
      timeout: 20s
      retries: 10

  influxdb:
    image: $BUTLER_IMG_INFLUXDB
    environment:
      - INFLUXDB_UID=$BUTLER_INFLUXDB_UID
      - INFLUXDB_GID=$BUTLER_INFLUXDB_GID
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_MONITOR_STORE_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
    secrets:
      - influxdb-db-password
    volumes:
      - influxdb-data:/var/lib/influxdb:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ 204 -eq $$(curl --write-out %{http_code} --silent --location --head --output /dev/null localhost:8086/ping?wait_for_leader=30s) ] || exit 1"]
      timeout: 40s
      retries: 3
      interval: 60s

  nginx:
    image: $BUTLER_IMG_NGINX
    environment:
      - NGINX_UID=$BUTLER_NGINX_UID
      - NGINX_GID=$BUTLER_NGINX_GID
    volumes:
      - $BUTLER_HOME/nginx/conf.d:/etc/nginx/conf.d:ro
      - $BUTLER_HOME/nginx/stream.d:/etc/nginx/stream.d:ro
      - $BUTLER_HOME/cert/ca/ca.crt.pem:/etc/nginx/cert/ca.crt.pem:ro
      - $BUTLER_HOME/cert/srv/$BUTLER_HOST/$BUTLER_HOST.crt.pem:/etc/nginx/cert/crt.pem:ro
      - $BUTLER_HOME/cert/srv/$BUTLER_HOST/$BUTLER_HOST.key.pem:/etc/nginx/cert/key.pem:ro
      - api-static:/var/www/api-static:ro
      - $BUTLER_HOME/fw:/var/www/api-media/fw:ro
    ports:
      - 8000:80/tcp
      - 8043:443/tcp
      - 8883:8883/tcp
    restart: unless-stopped

  api:
    image: $BUTLER_IMG_BUTLER_API
    depends_on:
      - mariadb
      - influxdb
    command: django-apps --preload -w 3 -b :8000 butler_api.wsgi
    environment:
      - BUTLER_HOME=/butler-api
      - BUTLER_HOST
      - BUTLER_DB_HOST=mariadb
      - BUTLER_DB_NAME=$BUTLER_MYSQL_DATABASE
      - BUTLER_DB_USER=$BUTLER_MYSQL_USER
      - BUTLER_DB_PASSWORD_FILE=/run/secrets/mariadb-db-password
      - BUTLER_TSDB_HOST=influxdb
      - BUTLER_TSDB_PORT=8086
      - BUTLER_TSDB_NAME=$BUTLER_INFLUXDB_DATABASE
      - BUTLER_TSDB_USER=$BUTLER_INFLUXDB_USER
      - BUTLER_TSDB_PASSWORD_FILE=/run/secrets/influxdb-db-password
      - BUTLER_API_DJANGO_SECRET_KEY_FILE=/run/secrets/api-django-secret-key
      - BUTLER_API_UID
      - BUTLER_API_GID
      - BUTLER_CERT_KEY_UID
      - BUTLER_CERT_KEY_GID
      - BUTLER_CERT_KEY_MODE
    secrets:
      - mariadb-db-password
      - influxdb-db-password
      - api-django-secret-key
    volumes:
      - $BUTLER_HOME/cert:/butler-api/media/cert:rw
      - $BUTLER_HOME/fw:/butler-api/media/fw:rw
    restart: unless-stopped

  xbee-gw:
    image: $BUTLER_IMG_XBEE_GW
    environment:
      - BUTLER_XBEE_GW_UID
      - BUTLER_XBEE_GW_GID
      - BUTLER_XBEE_GW_JWT_KEY_FILE=/run/secrets/xbee-gw-jwt-key
    secrets:
      - xbee-gw-jwt-key
    volumes:
      - $BUTLER_HOME/xbee-gw/config.json:/etc/butler-xbee-gateway/config.json:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0:rw"
    restart: unless-stopped

  grafana:
    image: $BUTLER_IMG_GRAFANA
    depends_on:
      - mariadb
      - influxdb
    command:
      - sh
      - -c
      - >-
        envsubst '\$$GF_DATABASE_USER \$$GF_DATABASE_PASSWORD \$$GF_DATABASE_HOST \$$GF_DATABASE_NAME'
        < /etc/grafana/grafana.ini.in > /etc/grafana/grafana.ini
        &&
        /run.sh grafana-app
    environment:
      - GRAFANA_UID=$BUTLER_GRAFANA_UID
      - GRAFANA_GID=$BUTLER_GRAFANA_GID
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_HOST=mariadb:3306
      - GF_DATABASE_NAME=$BUTLER_MYSQL_GRAFANA_DATABASE
      - GF_DATABASE_USER=$BUTLER_MYSQL_GRAFANA_USER
      - GF_DATABASE_PASSWORD_FILE=/run/secrets/mariadb-grafana-db-password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_DOMAIN=$BUTLER_HOST
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
    secrets:
      - mariadb-grafana-db-password
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - $BUTLER_HOME/grafana/grafana.ini.in:/etc/grafana/grafana.ini.in:ro
    restart: unless-stopped

volumes:
  mosquitto-data:
  mariadb-data:
  influxdb-data:
  api-static:
  grafana-data:

secrets:
  mariadb-root-options:
    file: $BUTLER_HOME/mariadb/root-options.cnf
  mariadb-db-password:
    file: $BUTLER_HOME/mariadb/db-password
  mariadb-grafana-db-password:
    file: $BUTLER_HOME/mariadb/grafana-db-password
  influxdb-db-password:
    file: $BUTLER_HOME/influxdb/db-password
  influxdb-grafana-db-password:
    file: $BUTLER_HOME/influxdb/grafana-db-password
  api-django-secret-key:
    file: $BUTLER_HOME/api/django-secret-key
  xbee-gw-jwt-key:
    file: $BUTLER_HOME/api/django-secret-key
